### ISSUE TITLE
[JENKINS-68250] Icon defaults to help.png, which was deleted in Jenkins 2.333

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [jenkinsci/sidebar-link-plugin#40]
_This issue is also tracked as [JENKINS-68250](https://issues.jenkins.io/browse/JENKINS-68250)._

### Jenkins and plugins versions report

I have not reproduced this bug yet, but I think it will occur when Sidebar Link 2.1.0 is used with Jenkins 2.333 or later.

### What Operating System are you using (both controller, and any agents involved in the problem)?

Any

### Reproduction steps

1. Define a sidebar link in the global configuration, without specifying an icon.
2. Save the settings.
3. View the sidebar on the main page.

### Expected Results

The sidebar link should have a default icon.

### Actual Results

Icon won't load.

### Anything else?

PR <https://github.com/jenkinsci/sidebar-link-plugin/pull/25> made LinkAction use "static/efbf17e4/images/16x16/help.png" as the default icon. As of Sidebar Link 2.1.0, LinkAction still does so:

<https://github.com/jenkinsci/sidebar-link-plugin/blob/fa77f63045894732918b5ade79bc867e429897bd/src/main/java/hudson/plugins/sidebar_link/LinkAction.java#L67-L69>

However, <https://github.com/jenkinsci/jenkins/pull/5778> deleted `war/src/main/webapp/images/16x16/help.png` from the Jenkins core. This change was released in [Jenkins 2.333 (2022-01-31)](https://www.jenkins.io/changelog/#v2.333). The icon has been replaced with [war/src/main/webapp/images/svgs/help.svg](https://github.com/jenkinsci/jenkins/blob/f023108ec324d51d77da15890b2db8f1f76a61d3/war/src/main/webapp/images/svgs/help.svg), which was moved to that directory in <https://github.com/jenkinsci/jenkins/pull/5663> and released in [Jenkins 2.308 (2021-08-24)](https://www.jenkins.io/changelog/#v2.308).

There is a migration guide in [Icon path to icon class migration ](https://www.jenkins.io/doc/developer/views/icon-path-to-icon-class-migration/) but it looks a bit difficult to apply in the Sidebar Link plugin. I think the best fix is to save an empty string as the icon file name in the persistent configuration and substitute a version-specific default when the link is rendered. This would require separating LinkAction.getIconFileName() to two methods: one that implements Action.getIconFileName() and another that is used for the configuration UI and CasC. I hope `@Symbol` can be used to retain compatibility with existing CasC `jenkins.yaml` files.

Alternatively, Sidebar Link could ship with its own copy of `help.svg` and always default to that.

**Comment by KalleOlaviNiemitalo** [comment]
> This would require separating LinkAction.getIconFileName() to two methods

Like there is [LinkAction.getUrlName()](https://github.com/jenkinsci/sidebar-link-plugin/blob/fa77f63045894732918b5ade79bc867e429897bd/src/main/java/hudson/plugins/sidebar_link/LinkAction.java#L77-L83) for the Action interface and [LinkAction.getUnprotectedUrlName()](https://github.com/jenkinsci/sidebar-link-plugin/blob/fa77f63045894732918b5ade79bc867e429897bd/src/main/java/hudson/plugins/sidebar_link/LinkAction.java#L93-L96) for the [text box in links.jelly](https://github.com/jenkinsci/sidebar-link-plugin/blob/fa77f63045894732918b5ade79bc867e429897bd/src/main/resources/hudson/plugins/sidebar_link/links.jelly#L7-L9).

**Comment by KalleOlaviNiemitalo** [comment]
> I hope @Symbol can be used to retain compatibility

Nope, [`@interface Symbol` has `@Target({TYPE})`](https://github.com/jenkinsci/lib-symbol-annotation/blob/52af4c3171df607e2b500243b11abf70ef6400c2/src/main/java/org/jenkinsci/Symbol.java#L44), so LinkAction cannot define `@Symbol("iconFileName") public String getIconFileNameWithoutDefault()`to make CasC call this method when it exports the current configuration to YAML. Instead, sidebar-link-plugin could perhaps implement [Configurator](https://github.com/jenkinsci/configuration-as-code-plugin/blob/configuration-as-code-1.55/plugin/src/main/java/io/jenkins/plugins/casc/Configurator.java) for that purpose.

**Comment by KalleOlaviNiemitalo** [comment]
I tried setting just "help" as the icon name, without any directory path or file extension, and Jenkins 2.319.3 rendered a question mark icon as SVG.

```XML
    <hudson.plugins.sidebar__link.LinkAction>
      <url>http://example.org/</url>
      <text>Example</text>
      <icon>help</icon>
    </hudson.plugins.sidebar__link.LinkAction>
```

```HTML
<div class="task "><span class="task-link-wrapper "><a href="http://example.org/" title="Example" class="task-link "><span class="task-icon-link"><svg viewBox="0 0 24 24" focusable="false" class="svg-icon icon-help icon-md"><use href="/jenkins/static/1bfb45e3/images/material-icons/svg-sprite-action-symbol.svg#ic_help_24px"></use></svg></span><span class="task-link-text">Example</span></a></span></div>
```

That might work as a default icon, then. However:

- I did not test with older or newer versions of Jenkins.
- That this works at all seems to be a side effect of how [actions.jelly](https://github.com/jenkinsci/jenkins/blob/8a29e8858b49da45c0071f690d4ceebe8db2f18f/core/src/main/resources/lib/hudson/actions.jelly#L40) chooses the icon. Icon names that are not file names should apparently be returned from [IconSpec.getIconClassName()](https://github.com/jenkinsci/jenkins/blob/8a29e8858b49da45c0071f690d4ceebe8db2f18f/core/src/main/java/org/jenkins/ui/icon/IconSpec.java#L37-L44) and not from [Action.getIconFileName()](https://github.com/jenkinsci/jenkins/blob/8a29e8858b49da45c0071f690d4ceebe8db2f18f/core/src/main/java/hudson/model/Action.java#L99).
- The form validation in the sidebar link configuration displayed an ugly warning about "Image does not exist". On the other hand, that warning would be avoided if the "help" default applied only during rendering and were never displayed on the configuration page.

Perhaps Sidebar Link could use something like `org.jenkins.ui.icon.IconSet.icons.getIconByClassSpec("icon-help icon-md").getUrl()` to get a default path for Action.getIconFileName(). That would depend on <https://github.com/jenkinsci/jenkins/pull/5072> in Jenkins 2.269, I think. It seems easier to ship a copy of help.svg in the sidebar link plugin. Or even switch the default to a different icon altogether.

**Comment by KalleOlaviNiemitalo** [comment]
[A comment in JENKINS-67844](https://issues.jenkins.io/browse/JENKINS-67844?focusedCommentId=422149&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-422149) mentions [custom symbols](https://www.jenkins.io/doc/developer/views/symbols/) intended for the sidebar. Of the existing symbols, [help-circle.svg](https://github.com/jenkinsci/jenkins/blob/4c9a9be6154ab1cad7c3f0b7f282df66f5aeb150/war/src/main/resources/images/symbols/help-circle.svg) is most similar to the current help icon. However, I'm not sure a help icon is even appropriate as the default icon. Plugins cannot install [custom symbols](https://www.jenkins.io/doc/developer/views/symbols/#custom-symbols) yet.

Anyway, Action.getIconFileName() must be implemented to get the icon into the sidebar, and I don't see how to use symbols there in a supported way, so it seems best to ignore symbols for now.

**Comment by KalleOlaviNiemitalo** [comment]
@NotMyFault, you have been replacing icons in other plugins for Jenkins. Can you recommend what to do here? To summarize:

- The Sidebar Link plugin lets the user type an icon file name for each link, and saves that string in within a GlobalConfiguration or NodeProperty or FolderProperty or JobProperty.
- If the user does leaves the icon file name empty, then it defaults to "static/efbf17e4/images/16x16/help.png", and the plugin saves that. However, help.png was deleted in Jenkins 2.333.
- The plugin defines a LinkAction class that implements Action.getIconFile() by returning the previously saved string. That is indirectly called from [actions.jelly](https://github.com/jenkinsci/jenkins/blob/8a29e8858b49da45c0071f690d4ceebe8db2f18f/core/src/main/resources/lib/hudson/actions.jelly#L40) in core, perhaps from elsewhere too.
- pom.xml currently sets 2.263.4 as jenkins.version. That version has [war/images/help.svg](https://github.com/jenkinsci/jenkins/blob/jenkins-2.263.4/war/images/help.svg) but I'm not sure it can be directly used as Action.getIconFile().

Should the Sidebar Link plugin reference an icon provided by Jenkins, or should it carry its own icon?

If using an icon provided by Jenkins, then should that be done by returning a specific string from Action.getIconFile(), or by taking over with a LinkAction/action.jelly file?

The plugin should also be changed to stop saving the default icon file name as part of the per-icon settings, but I think I'll figure out how to do that on my own.

**Comment by NotMyFault** [comment]
> @NotMyFault, you have been replacing icons in other plugins for Jenkins. Can you recommend what to do here?

You can ship your own default icon for sure, but I would go with bumping the baseline, because that is a change you definitely do in a foreseeable future, which does then defeat the addition of a temporary custom icon just to keep an old baseline, which already is more than two years old, in this case.
