### ISSUE TITLE
Support for ionicon

### ISSUE THREAD

**Issue by jonesbusy** [jenkinsci/sidebar-link-plugin#45]
### What feature do you want to see added?

Hi,

It would be amazing if this plugin support ionicon (For example like the custom-folder-icon plugin https://github.com/jenkinsci/custom-folder-icon-plugin/pull/85)

What we have

- We have some ionicon on the userContent folder
- The SVG have the stroke="currentColor" but because they are loading by <img>, style is not applied

See the issue with dark-theme (We expect the SVG to be white)

![sidebar_link_ionicon](https://user-images.githubusercontent.com/825750/193998661-7cd076aa-f113-429e-a8ee-9a0b62fe10b1.PNG)

Best regards,

**Comment by damianszczepanik** [comment]
What is the location of the icon which you would like to use ?

**Comment by jonesbusy** [comment]
My icon are for the moment on the userContent folder but the idea of this issue is to have something similar to : https://github.com/jenkinsci/custom-folder-icon-plugin/pull/85

Where we can reause existing ionicons from the provider plugin.

**Comment by damianszczepanik** [comment]
If you want to display resource out of your Jenkins then you need to configure security settings to allow this

**Comment by jonesbusy** [comment]
An other example to illustrate desired feature

This new plugin : https://plugins.jenkins.io/customizable-header/ support specifying symbol that are theme aware

It also avoid uploading the SVG on userContent when they are available as symbol

Using dark theme

![jenkins_dark](https://github.com/jenkinsci/sidebar-link-plugin/assets/825750/9628ccd9-6ef6-4850-80fb-67e87b10b9f8)

Using default theme

![jenkins_default](https://github.com/jenkinsci/sidebar-link-plugin/assets/825750/919c4b76-fee3-42de-b5e5-46d3b0aa4435)

Configuration of mentionned plugin allow different strategies for icon (upload on userContent and mentioning an existing symbol)

![symbol_selection](https://github.com/jenkinsci/sidebar-link-plugin/assets/825750/e0e61212-0006-480a-8384-5cd74a1dd4f2)

**Comment by mawinter69** [comment]
You can already use ionicons:
In the `Link Icon` just write e.g.
`symbol-jenkins plugin-ionicons-api` and you will get the Jenkins logo shown. 
You can also refer to symbols from Jenkins itself (https://github.com/jenkinsci/jenkins/tree/master/war/src/main/resources/images/symbols) by just writing e.g. `symbol-<filename>` though almost all icons in core are also available in ionicons. You can also load a symbol from any other installed plugin that has symbols with `symbol-<name> plugin-<pluginname>`

**Comment by jonesbusy** [comment]
Excellent thanks! I didn't know the symbol where also resolved by `getIconFileName`.

I just submitted a PR to update the form validation
