### ISSUE TITLE
Could you just add an example image or two so users can see what it looks like?

### ISSUE THREAD

**Issue by red8888** [jenkinsci/sidebar-link-plugin#64]
### Describe your use-case which is not covered by existing documentation.

This plugin _seems_ like what I need, but I don't want to have to install it, set it up, and test it before getting to see what it actually looks like.

Is it too much to just throw an example image or two into the docs? Just a screenshot of a build status page with a sidebar link this thing added.

Thanks!

**Comment by damianszczepanik** [comment]
Run test Jenkins from jar file and check if this is what you need

**Comment by red8888** [comment]
@damianszczepanik what does "Run test Jenkins from jar file" mean? Is there a way to test it and look at it without having to install it as a plugin?

**Comment by damianszczepanik** [comment]
Setup Jenkins from jar file so you can test it locally
