### ISSUE TITLE
It's impossible to delete all global sidebar links

### ISSUE THREAD

**Issue by mawinter69** [jenkinsci/sidebar-link-plugin#69]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Version 2.3.0 of sidebar-link
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

doesn't matter

### Reproduction steps

1. Go to manage Jenkins -> configure
2. Add a sidebar link
3. Press Apply
4. Delete all sidebar links
5. Press Save

### Expected Results

No sidebar links are shown/configured

### Actual Results

The sidebar link is still there. 
When you have 2 sidebar links and try to delete both at the same time, both will stay.

### Anything else?

Deleting all sidebar links of a jobs and folders works fine

**Comment by damianszczepanik** [comment]
Interesting issue, for now I have forwarded it to Jenkins team as this is not only for this plugin - rather general issue
https://issues.jenkins.io/browse/JENKINS-72183

**Comment by damianszczepanik** [comment]
https://issues.jenkins.io/browse/JENKINS-72018

**Comment by mawinter69** [comment]
I disagree to close this, the issue still persists with latest Core sources. And fixing this in core is probably a bigger effort and I don't expect a fast solution (if ever).

**Comment by mawinter69** [comment]
fixing here is easy

**Comment by damianszczepanik** [comment]
True, I've read information about fix version and understood that this will be released soon
